### ISSUE TITLE
[FEATURE]: 강의 계획서 수정에 대한 요구

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#101]
**Description**
지금의 강의 계획서 수정은 아래 3가지 조건을 모두 만족해야 한다.
1. 작성자 본인
2. 멘토가 모두 승인하지 않았을 경우
3. 수강생이 없는 경우(수강생이 있을 경우 멘토 승인을 취소 할 수 없다.)

그런데 잘못 작성된 강의계획서로 인해서 수강 신청을 못하는 학생(제한 인원을 잘 못 입력), 내용 수정을 할 수 없는 문제 등으로 BLMS에서와 같이 수정 할 수 있도록 조정되는 것이 요구되고 있다.

1. 담당 교사 수정 가능
2. 강의실, 시간표를 제외한 정보는 수시로 수정 가능
3. 승인 취소 시에는 작성자가 강의실, 시간표도 수정 가능

그래서 일단 문제를 해결하기 위해 해당 사항을 수정하여 적용하고 신뢰성 문제에 대한 부분을 추후에 다시 고민해보는 것이 좋을 것으로 판단된다.

일단 직접 수정해서 PR을 올릴 예정인데 추후에 확인해주기 바랍니다.

**Comment by jessie129j** [comment]
승인된 syllabus가 수정될 수 없다는 전제하에 프로그래밍을 했기 때문에  이를 수정할 시 고려해야 할 사항이 몇가지 있습니다.

1. syllabus가 수정되면 연결된 enrollment 정보도 일괄적으로 변경되어야 합니다.

2. syllabus의 subject가 바뀌면 enrollment의 evaluation도 시즌 평가 양식에 따라서 바뀌어야 합니다.

그리고 지금도 승인 취소된 상태에서는 멘토, 강의실 및 시간을 변경할 수 있습니다.

**Comment by devgoodway** [comment]
아 그러면 좀 어렵겠는데
지금 enrollment api에는 syllabus에 포함된 정보를 수정하는 기능이 없는거지?

**Comment by jessie129j** [comment]
네 enrollmentAPI에는 수강신청/취소/평가 기능밖에 없습니다.

**Comment by devgoodway** [comment]
그러면 일단 코드를 수정하는 방법 대신에 수강 중인 인원을 수강 취소 시키고 작성자가 수정하는 방법으로 해봐야겠다.

**Comment by jessie129j** [comment]
넵 그에 관해서 멘토링 페이지에서 #102 이슈를 발견했는데 수정중입니다
