### ISSUE TITLE
[FEATURE] 강의계획서 관련

### ISSUE THREAD

**Issue by jessie129j** [devgoodway/school-information-system#104]
아래 제안사항은 개발이 끝난 상태인데 아직 합치진 않았습니다.
@devgoodway 선생님께서 한 번 검토해주시면 좋을 것 같습니다.

# Description
## 1. 강의계획서 상태에 '미승인', '승인됨' 외에 '승인중' 추가
멘토가 둘 이상이며 한 명 이상이 승인한 경우가 이에 해당함. 

멘토가 둘 이상(A와 B)일 때,
 1. A와 B 모두 승인하지 않은 경우
     - '미승인' 상태로 띄워짐
 2. A가 승인한 후(A: 승인, B: 미승인)
    - 기존 방식: '미승인' 상태로 띄워짐
    - 제안 방식: '승인중' 상태로 띄워짐 + 클릭시 팝업으로 승인 현황 확인 가능
 3. B가 승인한 후(A: 승인, B: 승인) 
    - 기존 방식: 승인된 상태로 띄워짐

## 2. [담당 수업 목록]페이지에서 테이블을 통한 승인 및 승인 취소

관련 이슈: #92 

아래 영상 참고

https://user-images.githubusercontent.com/19641212/218244551-e7596a67-e2b3-4223-bc9e-fe4a6fa89ae6.mp4

## 3. [개설 수업 상세 페이지]와 [담당 수업 상세 페이지]간 이동하는 버튼 추가
1. [개설 수업 상세 페이지]에서 개설자와 멘토가 동일한 경우 [담당 수업 상세 페이지]로 이동할 수 있는 버튼 추가됨
2. [멘토링 수업 상세 페이지]에서 개설자와 멘토가 동일한 경우 [멘토링 수업 상세 페이지]로 이동할 수 있는 버튼 추가됨

멘토링 상세 페이지에서 수업계획서를 수정 및 삭제하기 위해 여러 페이지를 이동하는 것이 불편한 것 같아서 추가해보았습니다.

아래 영상 참고

https://user-images.githubusercontent.com/19641212/218244844-deb644e6-26e9-4a7a-8648-ba8615aa4dba.mp4

## 4. [수강/개설/담당 수업 상세 페이지]에서 [수강/개설/담당 수업 목록]으로 이동하는 기능
이미 들어가있는 기능인데 설명을 따로 안드린 것 같아서 알려드립니다

아래 영상 참고

https://user-images.githubusercontent.com/19641212/218244880-a4b3d2e1-ae0d-41b7-a9ab-d71cad0f3b33.mp4

지금 보니 마우스를 해당 영역에 놓았을 때  '목록으로 이동'같은 description이 뜨면 좋을 것 같네요

**Comment by devgoodway** [comment]
모두 필요했던 기능인데 잘 만들어져서 좋아요!
합쳐도 될 것 같아요!
사용자 피드백들이 들어오고 있는데 필요한 것들은 잘 보완 할 수 있으면 좋을 것 같아요^^

**Comment by devgoodway** [comment]
한 가지 강의계획서에서 추가됬으면 하는 것은 지도 교사에게 강의계획서 수정 권한이 부여되면 좋을 것 같아요
현실적으로 선생님이 직접 수정을 해야만 하는 상황이 많이 발생하기 때문에 필요할 것 같아요
수정이 필요한 경우 지도교사가 수정하고 만약 수강신청 이후라도 초대취소시키고 수정후 초대하는 방식으로 할 수 있을 것 같아요
