### ISSUE TITLE
[BUG] Notification

### ISSUE THREAD

**Issue by jessie129j** [devgoodway/school-information-system#105]
# Description

1. 학생들이 notification 보낼 수 없도록 막기
특정 학생에서 notification 전송 권한을 부여하는 기능은 추후 논의

2. 알림 수신하면 화면이 새로고침되는 것을 막기
강의계획서 작성하다 알림 수신하면 새로고침되서 다 날아감...

4. 알림 수신할 때 알림음 끄기
끄는게 나을 것 같다고 생각하는데 다른 분들 의견이 궁금합니다!

**Comment by devgoodway** [comment]
1. 막아두고 권한 설정 부여 할 수 있으면 좋을 것 같아요
2. 수정이 잘 되어야 겠네요!
3. 옵션이 있다면 알림음을 사용 할 수 있게 해도 좋을 것 같아요
