### ISSUE TITLE
[BUG] : 문서에서 생활기록부 양식 출력시 발생하는 오류

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#109]
**Description**
1. 2023학년도 1쿼터에서 문서를 출력 할 때 오류가 발생하면서 페이지가 로드되지 않음.
2. 문서에 창의적 체험활동 필드를 추가해서 출력했을 때 페이지 다운 현상이 생김.

**스크린샷**
1. 2023학년도 1쿼터에서 문서를 출력 할 때 오류가 발생하면서 페이지가 로드되지 않음.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/218315517-a83f9709-ad46-4bfe-b01d-159336b69013.png">

2. 문서에 창의적 체험활동 필드를 추가해서 출력했을 때 페이지 다운 현상이 생김.
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/22511259/218316789-16053587-4c65-4600-a672-bfe0aad09b88.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/218316810-287b1127-0057-44f5-b410-d9f657bc408e.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/218316820-cc86f541-dda2-4286-85b1-d3669bf05996.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/218316756-f5c1877d-8030-4033-97f9-5e50bad595d0.png">
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/22511259/218316883-2bb51ab1-84c9-4e1d-86ed-a348a42d145f.png">

**기타 사항**

**Comment by jessie129j** [comment]
@seedlessapple `docs>Index.tsx`와 `DataConnPopup.tsx`에서 학기의 양식(season.subjects.label, season.formEvaluation)에 따라 달라져야 하는 [교과], [과목], [멘토평가], [점수], [평가], [세부능력 및  특기사항] 항목을 코드에서 직접 사용하고 있는 것 같습니다.
해당 부분 수정해서 올릴테니 추후 확인 부탁드립니다!

**Comment by jessie129j** [comment]
`DataConnPopup.tsx`는 양식 수정 > 데이터셀 선택 > [데이터 연결]시 나타나는 데이터 연결 팝업입니다. 기존 방식에서는 데이터 선택 창에서 학교에 등록된 시즌의 교과목 헤더와 평가 양식이 반영되지 않습니다.

**기존 방식으로 양식을 설정할 때 발생하는 문제 예시 1**
1. 별무리초중등학교의 평가 양식
![image](https://user-images.githubusercontent.com/19641212/218773271-ebd917ca-4494-4e93-a811-c6f1605742d3.png)
2. 출력 양식의 데이터 연결창이 다음과 같이 뜸
![image](https://user-images.githubusercontent.com/19641212/218773910-3e6ebbea-f7ad-4161-8148-91bb4f2dddcc.png)

    2-1. [세부능력 및 특기사항] 선택하고 출력하면 '멘토평가'로 연결되지만 별무리초중등학교의 평가 양식에는 '멘토평가'가 없음(평가 양식에 등록된 '세부능력 및 특기사항'으로 연결되는게 아님)
    2-2. [평가, 점수, 멘토평가]는 별무리 고등학교에만 적용되는 평가 항목임

**기존 방식으로 양식을 설정할 때 발생하는 문제 예시 2**

1. 학교(tempSchool) 생성
4. 학교(tempSchool)에 학기 '2023학년도 1월' 생성
    2-1. '2023학년도 1월' 학기의 교과목 헤더를 다음과 같이 설정
![image](https://user-images.githubusercontent.com/19641212/218774009-5d1c941b-6efa-4a29-8b30-f642bce58ad9.png)
    2-2. '2023학년도 1월' 학기의 평가 양식을 다음과 같이 설정
![image](https://user-images.githubusercontent.com/19641212/218774046-d735be39-4167-4dea-b040-8b66fb656313.png)

3. 출력 양식의 데이터 연결창이 다음과 같이 뜸
![image](https://user-images.githubusercontent.com/19641212/218774334-9a2b25ad-b879-4394-b593-def331d2acfe.png)


    3-1. [대분류, 중분류, 소분류] 대신 [과목, 교과]가 뜸
    3-2. [세부능력 및 특기사항] 선택하고 출력하면 '멘토평가'로 연결되지만 학교(tempSchool)의 평가 양식에는 '멘토평가'가 없음


**수정된 방식**
1. 데이터 선택 창에서 학교에 등록된 시즌의 교과목 헤더와 평가 양식이 반영한다.
3. 시즌 평가 양식에서 평가 단위가 '학년도'인 평가 항목은 `연도별/${평가 항목}`으로 이름짓는다. 기존의 '세부능력 및 특기사항'은 '연도별/멘토평가'와 동일함

**수정된 방식 적용 - 별무리 고등학교**
![image](https://user-images.githubusercontent.com/19641212/218775058-7454a53e-d1eb-4295-a982-37abff2357c7.png)

**수정된 방식 적용 - 별무리초중등학교**
![image](https://user-images.githubusercontent.com/19641212/218775142-9f419a71-6edf-4ee4-96db-93781dfe303d.png)

**수정된 방식 적용 - 임시학교**
![image](https://user-images.githubusercontent.com/19641212/218775197-e2cc5b2b-8a9c-402b-864d-2ba6d5a80b99.png)

`109-bug-document` 브랜치에서 수정된 방식을 확인할 수 있습니다. 기존의 '생기부 제출용'은 제대로 출력되지 않으며, 새로 작성한 '생기부 제출용의 사본'이 새로운 방식을 적용한 버전입니다.
![image](https://user-images.githubusercontent.com/19641212/218775789-da9a5592-afab-4caf-beeb-9df84b96a26c.png)

@devgoodway @seedlessapple 확인해주시면 합치겠습니다~

**Comment by devgoodway** [comment]
수고했어요 지금 구현해준 것을 토대로 양식을 만들어보면서 확인해볼께요!

**Comment by jessie129j** [comment]
![image](https://user-images.githubusercontent.com/19641212/221562638-b4863071-5b1d-435d-8a35-4e929d1e053d.png)

bmr 아카데미에 수정된 생기부 양식 추가해뒀습니다
