### ISSUE TITLE
[BUG] : 수업계획서 강의실 수정 시 오류 발생

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#111]
**Description**
수업계획서 강의실 수정 시 강의실 없음 상태로 수정을 시도하면 강의실 없음으로 수강 신청 된 모든 수업 리스트가 체크박스를 채워서 수정 할 수 없는 상태가 됨

**스크린샷**
![image](https://user-images.githubusercontent.com/22511259/221166306-99c43d04-8672-4ce6-86bc-080c09bd3754.png)

**기타 사항**

**Comment by jessie129j** [comment]
월요일에 수정할 수 있을 것 같습니다

**Comment by devgoodway** [comment]
> 월요일에 수정할 수 있을 것 같습니다

그럼 일단 데이터에서 수정해볼께
