### ISSUE TITLE
[FEATURE]: Altsis 프로젝트 첫번째 버전을 완성하기 위한 확인사항

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#119]
**Description**
Altsis 프로젝트 첫번째 버전을 완성하기 위한 확인사항입니다.

**Bug**
- [x] #38
- 모바일 화면에서 메뉴 버튼 출력 오류 : 메뉴에 접근 할 수 있는 버튼이 출력되지 않는 문제
- 메뉴 클릭시 화면 전환 오류 : 메뉴가 축소되지 않고 화면이 전환 되지 않는 문제
- [x] #44
- 블럭 : 텍스트에서 정렬이 출력화면에서 정상적으로 작동하지 않음
- [x] #53 
- 기록 옵션에 파일 업로드 기능이 없음
- [x] #58 
- 저장 버튼 없이 추가 삭제가 바로 진행되도록 수정 필요.
- 선택과 사진 필드 등록 할 수 있도록 수정 필요.
- 기록 입력 옵션에 그룹별 입력 옵션 추가 필요.
- [x] #60  @jessie129j 
- 서버 재시동으로 조치하였으나 백엔드 서버 종료 원인 확인 및 조치 필요 
- [x] #121
- [x] #122 @jessie129j 

**Development**
- [ ] 일정과 시간표에서 수업 선택시 강의계획서로 이동 할 수 있도록 작업
- [ ] 일정에 시간표에 텍스트로 입력한 항목이 적용 될 수 있도록 작업
- [x] 수강신청 검색 테이블 테이블v2 적용하여 검색 할 수 있도록 작업 @jessie129j 
- [x] 강의계획서 출력 mentoring에서 강의계획서 조회하는 방식 말고 created 처럼 강의계획서 출력되도록 작업  @jessie129j 
- [ ] 출력 문서에 권한(학생,교사)과 활성화(활성화, 비활성화)를 설정하여 작업중인 문서 출력되지 않도록 하고 학생들도 확인 할 수 있는 문서 양식 제공(학점이수현황, 봉사활동현황, 자기평가작성현황 등으로 사용)
- [ ] search에 기록 부분 구현
- [x] enrollment 평가 결과에도 기록과 같은 누계 합산과 합산 기능 추가(학점이수현황)
- [x] 사이드바에 링크를 추가 할 수 있도록 작업(school DB에 등록) @jessie129j 
- [x] 테이블에서 페이지가 총 몇개 중에 몇번째인지 알 수 있게 표시
- [x] 교과/과목 옵션에 따라 과목 리스트 출력하는 형태 되도록 작업 @jessie129j 
- [x] 강의계획서 복사 @jessie129j 
- [x] 정렬 @jessie129j 

**Enhancement**
- [x] 소유자 페이지 작성 시 데이터 백업 관련 기능 필요 @jessie129j

**Comment by jessie129j** [comment]
사용자 - 이름 정렬
수업 목록 - 교과목 정렬

**Comment by jessie129j** [comment]
프로젝트에 등록한 것들은 체크해두겠습니다

**Comment by jessie129j** [comment]
제가 당장 작업할 수 있는 것들은 프로젝트에 status=backlog 상태로 올려두었습니다.  
우선순위 지정 부탁드려요!
