### ISSUE TITLE
[BUG] : 수업 개설 권한 설정 관련

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#122]
**Description**
1. 이름과 역할이 출력되지 않음.
2. 역할별 설정 작업시 수정 결과가 반영되지 않는 경우 발생

**스크린샷**
<img width="668" alt="image" src="https://user-images.githubusercontent.com/22511259/225655472-b370cfdf-33e8-4bb1-ac01-9a907007d684.png">

**기타 사항**

**Comment by jessie129j** [comment]
+ 사용자 검색 가능하도록

**Comment by jessie129j** [comment]
**[시즌 > 권한] 탭 업데이트**

1. 이름과 역할 출력되지 않는 문제 해결
2. 역할별 설정 작업시 수정 결과 반영되지 않는 문제 해결.
    - 연속 작업이 제대로 반영되지 않았었음.
        ex) {선생님: off, 학생: off} 상태에서 선생님 on, 학생 on 연달아 작업하면 학생만 on됨
    - 작업이 한 번 끝날 때마다 최신 상태 업데이트하여 해결.
3. 예외 사용자 선택시 select 대신 autoFill 적용해 검색 가능하도록 변경함.
4. 예외 목록 헤더를 [시즌 > 사용자]의 헤더와 같이 [역할]-[ID]-[이름] 순서로 변경함.
5. [시즌 > 권한] 탭 테이블에서 [Y], [N] 버튼으로 권한 설정하는 기능 추가

https://user-images.githubusercontent.com/19641212/226824879-537888f4-412b-42d0-8309-dbe7097749a7.mp4
