### ISSUE TITLE
[FEAT] 테이블 잔여 페이지 보이기

### ISSUE THREAD

**Issue by seedlessapple** [devgoodway/school-information-system#134]
+ 테이블 잔여 페이지 보이기
+ [FIX] 테이블 페이지 숫자로 이동시 마지막 페이지로 이동 하는 버그

**Comment by devgoodway** [comment]
![image](https://user-images.githubusercontent.com/22511259/228089474-a1463061-c2a2-4943-bd25-45a7825d7df5.png)

페이지가 1개일 때 Infinity로 표시되는 것 같아요. 
페이지가 1개일 때는 1로 표시되야 할 것 같아요.

**Comment by seedlessapple** [comment]
수정됬습니다
