### ISSUE TITLE
[FEAT] Syllabus / Enable to copy & paste syllabus

### ISSUE THREAD

**Issue by jessie129j** [devgoodway/school-information-system#155]

**Comment by jessie129j** [comment]
![녹화_2023_04_10_10_20_40_44](https://user-images.githubusercontent.com/19641212/230809093-4eb8d6f1-56cd-4340-b9e8-79fcf8a04072.gif)

**Comment by devgoodway** [comment]
![KakaoTalk_Photo_2023-04-25-16-26-21 002](https://user-images.githubusercontent.com/22511259/234204783-77550759-d51a-43e2-8c83-02ca5ae8903a.jpeg)
![KakaoTalk_Photo_2023-04-25-16-26-21 001](https://user-images.githubusercontent.com/22511259/234204805-f52e9221-b85d-4e63-880e-0bfba3b23c09.jpeg)

내 계정에서는 문제가 없는데 최혜영 선생님 계정에서는 수업을 불러오면 내용을 입력되지않는 문제가 있네요 확인해볼 필요가 있을 것 같습니다.

**Comment by jessie129j** [comment]
@devgoodway [거꾸로 한국사1]은 별무리초중등학교에서 작성하신 강의계획서네요.
별무리고등학교의 강의계획서 양식은 info 필드의 이름이 "학습내용.1주차"로 설정되어있는데
별무리초중등학교의 강의계획서 양식은 "학습내용1주차" 이렇게 설정되어 있어요.
형식이 맞지 않으니 자동으로 채워지지 않습니다.

**Comment by devgoodway** [comment]
아 그러네요 고마워요👍
