### ISSUE TITLE
[FEATURE]: 기록 그룹별 입력에 대한 제안

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#156]
**Description**
검색 테이블을 활용하는 방안을 제안한다.
- 단일 데이터의 경우 테이블에 사용자별 기록 데이터 필드를 나열하는 방법을 통해서 구현한다. 
- 누적 데이터의 경우 사용자 검색을 통해 그룹별 기록의 대상을 선정하고 선정된 사용자의 전체 누적된 데이터들이 나열 되도록 한다. 해당 상태에서 검색 테이블을 활용하여 검색 결과에 따른 데이터를 수정 할 수 있도록 한다. 
- 누적 데이터의 경우 그룹별 기록 대상을 선정하고 '신규'를 선택하여 해당 사용자에 대한 신규 누적 데이터를 생성한다.

1. 단일 데이터
- 전체 사용자에 대한 데이터 출력 -> 데이터 테이블을 이용한 검색 -> 정보 수정(RU)

2. 누적 데이터
- 사용자 선정 -> 데이터 출력 -> 데이터 테이블을 이용한 검색 -> 정보 수정(CRUD)

**Comment by jessie129j** [comment]
https://user-images.githubusercontent.com/19641212/231765220-3091ccfa-1104-435c-aa30-4bca3654489b.mp4


- 기록: 새로운 archive 입력 방식 적용
- 기록2: 기존 archive 입력 방식
