### ISSUE TITLE
[FEAT[ Archive / Allow students to view selected archive

### ISSUE THREAD

**Issue by jessie129j** [devgoodway/school-information-system#159]
특정 archive는 학생들도 조회할 수 있도록 설정

**Comment by jessie129j** [comment]
# 설정 화면
![image](https://user-images.githubusercontent.com/19641212/232305441-890c0e36-5570-48a0-90e9-bff1bc3a153f.png)

# 선생님 - 기록 화면
![image](https://user-images.githubusercontent.com/19641212/232305649-492d1474-cf9a-4c1c-8c80-64dc208da0df.png)

# 학생 - 내 정보 화면
![image](https://user-images.githubusercontent.com/19641212/232305719-55eee321-e2bd-4d50-af64-30ac7df17214.png)

**Comment by jessie129j** [comment]
학교>기록>에서 [자세히] 클릭시 기록 설정값 사라지는 에러 발생

**Comment by devgoodway** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/233996551-656964db-6ed6-4e39-a93a-8751a3918cec.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/233996691-54f1de68-0198-4adb-bd3c-3f6f16cf6665.png">

두명 이상의 학생을 선택하면 오류 발생

**Comment by jessie129j** [comment]
![image](https://user-images.githubusercontent.com/19641212/234007784-def80277-342e-4972-9782-5f5056d83b22.png)
admin 계정으로 접속시 [임시학교] 기록 편집 필드에서 [별무리 고등학교] 기록 편집 필드가 뜸

**Comment by jessie129j** [comment]
### patch1
> 두 명 이상의 학생을 선택하면 오류 발생

**관련 로그**
`2023-04-24 21:31:33,error,Assignment to constant variable.`

둘 이상의 학생을 선택해서 발생하는 오류는 아니었고, archive를 불러올 때 기존 archive가 없으면 새로 archive를 생성하는데 이 때 const로 지정한 변수에 새로운 값을 할당하려 해서 발생하는 오류였습니다. 해결 후 배포했습니다.

### patch2
> admin 계정으로 접속시 다른 학교 기록 편집 필드가 뜸

currentSchool 대신 해당 학교 정보를 props로 전달하여 로딩하게 수정 후 배포함
![image](https://user-images.githubusercontent.com/19641212/234014091-90f347bb-1df5-4e22-8845-f48eb9f776a6.png)
