### ISSUE TITLE
[BUG] : login error

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#205]
**Description**
altsis 로그인 시도시 400에러 발생

**스크린샷**
<img width="1439" alt="image" src="https://github.com/bmrdevteam/school-information-system/assets/22511259/0c4208d6-e56d-49ee-aa08-1d8048a850cd">

**기타 사항**

**Comment by devgoodway** [comment]
문제가 다시 발생했습니다!

**Comment by jessie129j** [comment]
# Description

## 400 CREDENTIAL_REQUIRED
구글 로그인 시 'credential'이 필요하나 해당 값이 전달되지 않았다는 에러
### SOLVED
실제로 전달되었으나 서버에서 이를 검증할 떄 오탈자가 있었음 

## 403 
이미 로그인한 상태에서 로그인을 시도할 시 발생하는 에러
### TODO
로그인 페이지 접속 시 이미 로그인한 상태인 경우 홈으로 리다이렉트
