### ISSUE TITLE
[BUG] : 사진 업로드시 알 수 없는 오류 발생

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#229]
**Description**
관리자가 아닌 사용자가 사진을 업로드 할 때 알 수 없는 오류 발생

**스크린샷**
스크린샷이 필요하다면 추가해 주세요
![KakaoTalk_Photo_2023-06-15-16-42-55 002](https://github.com/bmrdevteam/school-information-system/assets/22511259/bf9a2158-d458-49ea-9e69-626e5d4d6a71)
![KakaoTalk_Photo_2023-06-15-16-42-54 001](https://github.com/bmrdevteam/school-information-system/assets/22511259/f28bf407-16c2-4395-8fdc-c3b601e9ba95)

**기타 사항**

**Comment by jessie129j** [comment]
# Issue
일반 사용자의 CUploadFileArchive API 호출 시 403 Forbidden 에러 발생
=> 아카이브 파일을 업로드하는 CUploadFileArchive API의 권한이 `"admin"|"manager"`로 설정되어 있었음

# Fix
권한을 `"user"(로그인한 모든 사용자)`로 수정
