### ISSUE TITLE
[FEATURE]: 문서에 이미지 사이즈 조정 방법 필요

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#235]
**Description**
문서에서 이미지 사이즈를 조정하는 방법이 없어서 문서에 자연스럽게 배치 할 수가 없음.
이미지 사이즈를 조정하거나 표에 맞게 이미지 사이즈가 조정 될 수 있는 기능이 필요.

<img width="1165" alt="image" src="https://github.com/bmrdevteam/school-information-system/assets/22511259/c0edb3b5-2eda-4116-9a60-79ae728a3cdc">

**Comment by jessie129j** [comment]
# 기존 방식
양식이 아래와 같을 때 문서에서 사진 최대 너비가 120px로 고정되어 자동으로 늘어나지 않았습니다
![image](https://github.com/bmrdevteam/school-information-system/assets/19641212/4b15c134-0f66-4ec6-a18b-1ead09ee60b2)
![image](https://github.com/bmrdevteam/school-information-system/assets/19641212/41e63b88-2c16-449c-b4a3-179879818e2e)

# 수정 후
사진 최대 너비 설정을 삭제하여 사진이 셀을 다 채우도록 수정했습니다
![image](https://github.com/bmrdevteam/school-information-system/assets/19641212/09350ac3-74c9-4269-be1f-0066ae1f06e7)

**추가) 양식에서 셀 비율을 수정한 후**
![image](https://github.com/bmrdevteam/school-information-system/assets/19641212/c5d40971-6e06-42e1-a55a-ca5cbb587ceb)
![image](https://github.com/bmrdevteam/school-information-system/assets/19641212/ee3cf486-cdf0-45fe-8693-99c68eaed881)
