### ISSUE TITLE
[FEATURE]: 기록과 평가 필드의 순서를 재배치 할 수 있는 기능 필요

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#236]
**Description**
기록과 평가의 필드를 추가 또는 삭제 할 경우 입력 필드도 뒤에 붙는 형식이어서 순서를 조정 할 수 있는 기능이 필요합니다.

<img width="1367" alt="image" src="https://github.com/bmrdevteam/school-information-system/assets/22511259/102432e3-62a6-4f40-a1c4-da62735ae7c1">
<img width="834" alt="image" src="https://github.com/bmrdevteam/school-information-system/assets/22511259/066d0a58-96b0-4883-994a-1adb05bd462f">

**Comment by jessie129j** [comment]
# 테이블 순서 변경 기능 구현
테이블 컴포넌트에 순서를 변경할 수 있는 테이블 아이템 타입을 구현했습니다.
테이블 헤더에 아래와 같이 추가하여 사용할 수 있습니다 (`type: "rowOrder"`).
```
 {
      text: "순서",
      fontSize: "12px",
      fontWeight: "600",
      type: "rowOrder",
      width: "80px",
      textAlign: "center",
}
```

# 테이블 순서 변경 기능 적용
## 학교 - 기록
![녹화_2023_06_20_11_32_48_723](https://github.com/bmrdevteam/school-information-system/assets/19641212/ae533786-5eff-4d31-80f3-56eb28aff95f)

## 학교 - 링크
![녹화_2023_06_20_11_34_38_305](https://github.com/bmrdevteam/school-information-system/assets/19641212/138462e3-5c70-43fe-876a-e77be1e16d75)

## 학교 - 학기 - 교과목 & 강의실
![녹화_2023_06_20_11_35_39_55](https://github.com/bmrdevteam/school-information-system/assets/19641212/cab1ab15-705f-49ba-940d-a7f5ba93d599)
