### ISSUE TITLE
[BUG] : 양식에서의 표 병렬 배치가 실제 문서에서는 동작하지 않음

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#237]
**Description**
양식에서는 비율에 따라 표가 병렬 배치 되지만 문서에서는 동작하지 않습니다.

<img width="976" alt="image" src="https://github.com/bmrdevteam/school-information-system/assets/22511259/22f7ed2e-b367-4153-befc-653a28e8e7f2">
<img width="1157" alt="image" src="https://github.com/bmrdevteam/school-information-system/assets/22511259/0be4439b-c59e-4873-b1c4-9f6e6610a641">

**Comment by jessie129j** [comment]
이건 제가 해결할 수 없는 문제가 아닌 것 같아요😂
