### ISSUE TITLE
[BUG] : 양식 필터 오류

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#242]
**Description**
필터에 세특이 공백인 값은 출력하지 않도록 해두었는데 출력되는 문제가 발생함

<img width="1170" alt="image" src="https://github.com/bmrdevteam/school-information-system/assets/22511259/7b9b93de-18ce-4f62-a363-2776b7869cbb">

**Comment by seedlessapple** [comment]
추가하기는 했는데요 세특이 비어있으면 안되는거 아닌가요??

**Comment by seedlessapple** [comment]
그리고 세특 이름은 연도별/멘토평가 입니다

**Comment by devgoodway** [comment]
네 세특은 선택적으로 입력하고 있기 때문에 비어있을 수 있습니다.
그리고 필터에 공백 데이터를 제외하기로 했을 때 출력되지 않을 수 있게 되어야 할 것 같아요.

**Comment by seedlessapple** [comment]
https://github.com/bmrdevteam/school-information-system/commit/2a435a0455f5493723f5fc70db9fc79c5141e79a 추가됬습니다
