### ISSUE TITLE
[BUG] : 텍스트 입력시 줄바꿈이 안되거나 태그가 그대로 출력되는 문제

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#244]
**Description**
텍스트 입력 시 줄바꿈이 적용되지 않거나 br 태그가 출력되는 문제가 발생합니다.

![image](https://github.com/bmrdevteam/school-information-system/assets/22511259/df596036-3042-4427-9996-421cc8b4fbd8)

**Comment by jessie129j** [comment]
`<br/>`태그는 BLMS 데이터에 포함되어 있던 태그이며, ALTSIS로 작성한 평가에서는 나타나지 않습니다. 
DB에 enrollments를 모두 확인해서 태그를 삭제할 수는 있는데, 그렇게 할까요?

**Comment by devgoodway** [comment]
줄바꿈이 되는 것이 좋을 것 같기는 한데 그게 어렵다면 삭제하는 것이 좋을 것 같아요

**Comment by jessie129j** [comment]
BLMS 데이터에서 `<br/>`태그를 제거하면 태그 출력 문제는 해결할 수 있지만 문서 출력에서 줄바꿈은 관련 css를 수정해야 하는 것 같습니다. @seedlessapple 

## BLMS 데이터 평가예시
![image](https://github.com/bmrdevteam/school-information-system/assets/19641212/6be650f1-a5e3-4e64-a825-da50f46c0851)
```
 "evaluation": {
                "멘토평가": "프로그래밍을 간단하게 해봤을 때는 상당히 어려워서 내 진로는 이쪽이 아닐것이라는 걸 깨닳았다<br />\nppt만들때도 즐거웠던걸로 기억중<br />\n<br />"
            }
```
## ALTSIS 데이터 평가 예시
![image](https://github.com/bmrdevteam/school-information-system/assets/19641212/34c09a3e-049c-4e38-a1ac-c5443d732a12)
```
 "evaluation": {
                "멘토평가": "멘토 평가입니다\n멘토 평가입니다\n멘토 평가입니다"
            }
```

## 문서 출력 예시 (줄바꿈x)
![image](https://github.com/bmrdevteam/school-information-system/assets/19641212/392d4b62-c27e-4253-9459-6ce567829aec)
```
{
    "enrollments": [
        {
            "classTitle": "영화 분석 1.222222222222222222222222222",
            "subject": [
                "공통",
                "영화 분석"
            ],
            "evaluation": {
                "멘토평가": "멘토 평가입니다\n멘토 평가입니다\n멘토 평가입니다"
            }
        },
        {
            "classTitle": "어쩌구저쩌구 수업-- test",
            "subject": [
                "공통",
                "영화 기술 특별 강의"
            ],
            "evaluation": {
                "멘토평가": "프로그래밍을 간단하게 해봤을 때는 상당히 어려워서 내 진로는 이쪽이 아닐것이라는 걸 깨닳았다<br />\nppt만들때도 즐거웠던걸로 기억중<br />\n<br />"
            }
        }
    ]
}
```

**Comment by devgoodway** [comment]
이스케이프를 넣어서 저장해두고 출력할 때 반영하면 좋을 것 같아요

**Comment by jessie129j** [comment]
# 평가에서 `<br />` 태그를 제거했습니다.
개발 DB와 운영 DB에서 평가(evaluation)에 `<br />` 태그를 포함하는  enrollments 도큐먼트를 수정했습니다.
- 총 51,584개 도큐먼트 중 11,762개의 도큐먼트가 수정되었습니다(소요 시간: 152,239ms).
- 해당 작업으로 기능이 수정된 것은 없으므로 배포하지 않아도 됩니다.
- 문서 출력 화면에서 `\n` 문자에 대해 줄바꿈할 수 있도록 수정하면 될 것 같습니다.

## 수정 전 예시
```
{
   ...,
    "evaluation": {
        "자기평가": "선배님들과 재미있는 얘기를 나누었고  많은 심라학에 관련된 서적이나 사례에 대하여 재치있게 말씀드렸다 ",
        "멘토평가": "심리학 서적을 읽고 함께 나누면서 심리학에 대한 지식과 삶의 지혜를 얻는 시간을 가짐. 페르소나와 파랑새 신드롬과 문화심리학에 대한 발표를 하였음. <br />\n<슬픈 불멸주의자>, <죽기 전에 더 늦기 전에> 두 권의 책을 읽고 죽음에 관한 사색과 성찰을 나눔. 자신의 생각을 정리한 서평을 작성함. ",
        "점수": "99",
        "평가": "A"
    }
}
```

## 수정 후 예시
```
{
   ...,
    "evaluation": {
        "자기평가": "선배님들과 재미있는 얘기를 나누었고  많은 심라학에 관련된 서적이나 사례에 대하여 재치있게 말씀드렸다 ",
        "멘토평가": "심리학 서적을 읽고 함께 나누면서 심리학에 대한 지식과 삶의 지혜를 얻는 시간을 가짐. 페르소나와 파랑새 신드롬과 문화심리학에 대한 발표를 하였음. \n<슬픈 불멸주의자>, <죽기 전에 더 늦기 전에> 두 권의 책을 읽고 죽음에 관한 사색과 성찰을 나눔. 자신의 생각을 정리한 서평을 작성함. ",
        "점수": "99",
        "평가": "A"
    }
}
```
