### ISSUE TITLE
[BUG] : 평가가 교과만을 기준으로 작성되는 문제

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#251]
**Description**
평가가 교과만을 기준으로 작성되고 있음. 교과 과목을 포함한 교과목을 기준으로 평가 되도록 수정해야 함. 
7 | 정보미디어 | 웹프로젝트 | 본방사수 사이트 개조실습
8 | 정보미디어 | 웹프로젝트 | 웹 프로그래밍 수업 진도 계획 수업
위 2개를 동시에 듣는 학생의 평가가 같은 평가로 작성됨.

![image](https://github.com/bmrdevteam/school-information-system/assets/22511259/22493aa1-fba3-433c-b840-bf2a2c7cd493)
![image](https://github.com/bmrdevteam/school-information-system/assets/22511259/b9bea446-74dc-4344-b697-5eb01954a618)

**Comment by jessie129j** [comment]
교과목이 `{교과: 정보미디어, 과목: 웹프로젝트}`로 동일한 수업 아닌가요?
![image](https://github.com/bmrdevteam/school-information-system/assets/19641212/27170cdd-4445-4af4-acce-e4e5d76a41db)

**Comment by devgoodway** [comment]
아 내가 착각한 것 같은데 다시 확인해볼께요!

**Comment by devgoodway** [comment]
내가 착각했네요ㅠ 미안합니다!
