### ISSUE TITLE
[FEATURE] 시간표에서 수업 클릭 시 새 탭에서 수강 페이지로 이동

### ISSUE THREAD

**Issue by jessie129j** [devgoodway/school-information-system#254]

**Comment by jessie129j** [comment]
![녹화_2023_08_06_00_56_14_386](https://github.com/bmrdevteam/school-information-system/assets/19641212/bb9d6874-852e-429d-9bf8-bb6538c9ca1d)
1. 시간표에서 수강신청한 수업을 클릭하면 새 탭에서 수강 페이지 열림
2. 선생님이 담당 중인 수업을 수강신청한 경우 시간표에서 해당 수업을 클릭하면 멘토링 페이지로 이동할 것인지 묻고 ok면 멘토링 페이지로, no면 수강 페이지 열림
    - 수강 페이지: 자기평가 가능
    - 멘토링 페이지(담당 수업): 멘토평가 가능
4. 수업 개설하거나 수정할 때  강의실/시간 선택 시 개설된 수업 정보 팝업으로 확인 가능

**Comment by devgoodway** [comment]
오 학생들이 원하던 기능이 되었네요!
