### ISSUE TITLE
[BUG] : 문서 출력시 평가 정보에 과목, 교과가 출력되지 않는 문제

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#264]
### Description
**문제가 되는 화면**
![image](https://github.com/bmrdevteam/school-information-system/assets/22511259/f55863aa-c8a5-4fe5-a43e-05f92951d0ab)
![image](https://github.com/bmrdevteam/school-information-system/assets/22511259/394612e3-f54d-4376-b8d3-4447b5c70a1b)

**문서 출력시 데이터 호출 상태(해당 수업(67번) 교과,과목이 없음)**
![image](https://github.com/bmrdevteam/school-information-system/assets/22511259/6a8e007c-c710-4f7d-b660-a764384ad9fe)

**데이터 베이스 저장 상태(해당 수업 교과,과목이 없음)**
![image](https://github.com/bmrdevteam/school-information-system/assets/22511259/c3c3cb22-c7fa-492a-a578-b5bf047ad31f)

- 문서 출력시 일부 평가 정보에 과목, 교과가 없는 상태로 출력되는 문제가 발생 
- 데이터 베이스에서는 교과 과목이 들어가 있으나 문서 출력시에는 과목과 교과가 없는 상태로 출력 됨
- 문제되는 enrollment(_id : 6440ebb3b12158a0d57c40ad)의 정보를 확인해 보았으나 정상적으로 기록되어있음

**Comment by jessie129j** [comment]
방금 원인 파악해서 해결했는데 혹시 확인 가능하신가요?

**Comment by jessie129j** [comment]
# Troubleshooting

**요약**
- 예전에 테스트 학기를 생성하고 삭제하면서 관련 데이터가 삭제되지 않아 발생한 문제였음. 
- '학기 삭제 시 관련 데이터 삭제' 기능이 구현된 상태이기 때문에 다시 발생할 가능성 낮음.

**원인**
1. 올해 2월쯤 배포 환경에서 테스트 학기와 syllabuses, enrollments가 생성됨
    - season: `{ "_id": "63d982f567f56dbb2382c171", "schoolName": "별무리 고등학교",  "year": "2023학년도", "term": "테스트" }`
    - syllabuses는 3개의 documents로 각각 subject가 ["체육", "축구"], ["과학", "과학"], [ "수학", "수학Ⅰ"] 였음
    - enrollments는 55개

3. 해당 season 도큐먼트는 삭제되었으나 관련된 syllabuses, enrollments는 삭제되지 않았음. 
    - season 삭제 시 관련된 데이터(enrollment, syllabus, registration)를 함께 삭제하는 기능을 구현하기 전에 삭제된 것으로 추정됨 (#201)
  
4. 문서 페이지에서 학생의 enrollment를 조회할 때 테스트 학기의 enrollment가 함께 조회되었고, 테스트 학기가 삭제되었기 때문에 테스트 학기의 라벨 정보("교과", "과목")을 불러오지 못한 상태에서 enrollment 평가 정보를 압축하면서 `{"교과": "과학", "과목": "과학"}` 정보가 누락됨

**해결**
1. 삭제된 테스트 학기에 관련된 데이터(enrollments, syllabuses)를 모두 삭제함

2. 해당 학생 정보를 출력할 때 이슈가 생기지 않는 것을 확인함

**Comment by devgoodway** [comment]
애고 늦은시간에 고생했어요! 깔끔한 정리에 이해가 잘되었습니다! 수고했어요!
