### ISSUE TITLE
[BUG] : 학생 선택 정보가 유지되면서 발생하는 문제

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#269]
**Description**
기록에서 학생 선택하여 작업 한 이후에 수업에서 초대기능을 사용하면 기존에 선택되어있던 학생이 선택되어 초대되는 문제가 발생함

**Comment by jessie129j** [comment]
아래 케이스에서는 재현이 안되는데 문제를 더 자세히 설명해주시면 좋을 것 같아요.

1. 학생 A 선택해서 기록 → A가 수강하지 않는 수업에서 [초대] 선택 → A가 선택된 상태가 아님

2. 학생 A 선택해서 기록 → A가 수강하는 수업에서 [초대] 선택 → A가 선택된 상태가 아님

**Comment by devgoodway** [comment]
나도 다시 재현하려니까 안되네요ㅠ
다시 문제가 발생하면 다시 올릴께요!
