### ISSUE TITLE
[BUG] : 학기 중간에 사용자를 등록하면 권한이 부여되지 않는 문제

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#270]
**Description**
<img width="1434" alt="image" src="https://github.com/bmrdevteam/school-information-system/assets/22511259/f5129692-46e0-4574-868c-b8c8c00f83f9">

학생이 편입하여 학기 중간에 추가하였는데 권한이 부여되지 않아 예외 목록으로 추가하니 권한이 부여되었음.

**Comment by jessie129j** [comment]
# Report
registration을 생성하는 로직에서 permission을 따로 설정하지 않아 기본값(false)으로 설정되는 버그였습니다.
registration 생성 시 season을 참조하여 permission을 설정하도록 수정했습니다.

**추가 작업**
- season 권한에 예외로 등록된 registration 삭제 시 예외 목록에서도 삭제
- season 권한에 예외 중복 등록 요청 시 마지막 요청 반영
  - user01이 예외적으로 허용된 상황에서 '비허용'으로 등록 시 '비허용'으로 변경
  - user01이 예외적으로 허용된 상황에서 '허용'으로 등록 시 무시
  - user01이 예외적으로 비허용된 상황에서 '허용'으로 등록 시 '허용'으로 변경
