### ISSUE TITLE
[FEATURE]: 아카데미 별 백업 기능 구현

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#273]
# Description
지금은 root의 admin 계정으로만 백업이 가능한데 academy의 admin으로도 백업 할 수 있는 기능을 구현 할 필요가 있다. academy 단위로 독립적으로 운영하고 있기 때문에 필요한 기능으로 보임.

추가적으로 백업 데이터를 수정해서 업로드 할 수 있도록 하면 데이터 이전 시 유용하게 사용 할 수 있음.

**Comment by smaker** [comment]
## TEST LIST

- [ ] 학교 복구 테스트
- [x] 사용자 복구 테스트
- [ ] 기록 복구 테스트
- [ ] 학기 복구 테스트
- [ ] 등록 정보 복구 테스트
- [ ] 강의계획서 복구 테스트
- [ ] 수강 정보 복구 테스트
- [x] 양식 복구 테스트
- [ ] 알림 복구 테스트
