### ISSUE TITLE
[FEATURE]: 양식 관리 페이지 수정

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#274]
# Bug
![image](https://github.com/bmrdevteam/school-information-system/assets/22511259/b23ded28-7764-48e2-b076-55e68b8af12e)
양식 관리 페이지에서 리스트 형으로 볼 때 에디터로 들어가는 버튼이 없음.
# Description
- 격자 모양보다 리스트를 기본 페이지로 구성하도록 수정

**Comment by smaker** [comment]
## TODO
- [x] 양식 관리 페이지에서 리스트 형으로 볼 때 "수정" 버튼 추가
- [ ] 수정 페이지로 넘어갔다가 뒤로 돌아왔을 때, 이전에 선택한 리스트 스타일 유지되도록 개선 (router에 props 넘기면 될 것 같음)
