### ISSUE TITLE
[BUG] : 강의계획서 수정 오류

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#288]
**Description**
강의계획서의 시간과 장소를 제외한 내용은 수정 가능해야 하는데 다음과 같은 오류가 발생함.
교과/과목명을 바꾸거나 멘토를 추가하는 상황에서 해당 메세지 출력됨

![KakaoTalk_Photo_2023-09-04-14-44-29](https://github.com/bmrdevteam/school-information-system/assets/22511259/c92b7a65-d327-452f-9c71-6217f87bc60e)

**Comment by jessie129j** [comment]
혹시 멘토가 아닌 작성자가 수정하는 경우인가요?
멘토가 아닌 작성자는 승인된 강의계획서를 수정할 수 없습니다.

예시 1. 
1. 사용자1이 강의계획서 생성 + 사용자2를 멘토로 등록
2. 사용자2가 강의계획서 승인
3. 사용자1이 강의계획서 수정 🚫

예시 2. 
1. 사용자1이 강의계획서 생성 + 사용자2를 멘토로 등록
2. 사용자2가 강의계획서 승인
3. 사용자2가 강의계획서 수정 ✅

예시 2. 
1. 사용자1이 강의계획서 생성 + 사용자1을 멘토로 등록
2. 사용자1이 강의계획서 승인
3. 사용자1이 강의계획서 수정 ✅

# 관련 이슈
https://github.com/bmrdevteam/school-information-system/issues/176#issuecomment-1545014577 in [[FEAT] 수강생이 있는 강의계획서 수정](https://github.com/bmrdevteam/school-information-system/issues/176)
> 1. **멘토**는 승인 상태, 수강생이 있는 상태에서도 강의계획서를 수정할 수 있음
> 2. 멘토가 수강생이 있는 강의계획서를 수정하는 경우 안내문 출력
>    ![image](https://user-images.githubusercontent.com/19641212/237853219-a1398065-b69e-44b7-a55b-8bda0bd9abf9.png)

**Comment by devgoodway** [comment]
멘토인 사용자가 수정을 시도했을 때 발생합니다.
수정 페이지로 들어가서 내용을 수정하고 제출하면 위와 같은 문제가 발생하는데 교사 권한만 있는 계정에서는 동일한 문제가 발생하고 있는 것 같아요.

**Comment by jessie129j** [comment]
> 예시 2. 
> 1. 사용자1이 강의계획서 생성 + 사용자2를 멘토로 등록
> 2. 사용자2가 강의계획서 승인
> 3. 사용자2가 강의계획서 수정 ✅

이 경우일 때 발생한다는 말씀이시죠?

**Comment by jessie129j** [comment]
위 경우에서 정상적으로 작동하는데 어떤 수업인지 자세히 알려주시면 다시 확인할게요
`해당 수업이 개설된 학기 / 수업 명 / 개설자 / 멘토 / 수업을 수정하려는 멘토`

**Comment by devgoodway** [comment]
네 해당 멘토가 본인이 작성하지 않은 계획서를 수정 할 때 해당 문제가 발생합니다.
아래 수업이 문제가 발생하는 수업입니다!

|학교|해당 수업이 개설된 학기|교과|과목|수업명|개설자|멘토|수업을 수정하려는 멘토|
|---|---|---|---|---|---|---|---|
|별무리 고등학교|2022학년도 2쿼터|음악|음악실기|ㅇㄹ & ㅂㅇㅅ|문하진|박수민|박수민|
