### ISSUE TITLE
[FEATURE]: 문서 페이지 모바일시 메뉴 가로 정렬 되도록 수정

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#311]
**Description**
![image](https://github.com/bmrdevteam/school-information-system/assets/22511259/1c7b86b0-8a6a-4e07-9c18-6e7053ac2621)
모바일 화면에서 세로를 유지하면서 이름을 선택하는 것이 불가능해진다.
메뉴가 가로로 자연스럽게 정렬되도록 수정하면 좋겠다.

**Comment by smaker** [comment]
해당 이슈의 내용이 정확히 어떤 것인지 이해하지 못하였습니다.
정확히 설명 부탁드립니다.

**Comment by devgoodway** [comment]
> 해당 이슈의 내용이 정확히 어떤 것인지 이해하지 못하였습니다. 정확히 설명 부탁드립니다.

정확하게 아래 부분이 모바일 화면에서 가로 상태를 유지하면서 이름을 검색 할 수 없는 문제가 있습니다.
그래서 모바일 환경에서 오브젝트를 세로로 배치해서 문제를 해결하면 좋겠다는 이야기입니다.
예를 들어 아래 처럼 화면을 만들 수 있을 것 같습니다.
학생 선택 
[10학년] [이름검색]
[양식선택] [인쇄]

![image (2)](https://github.com/bmrdevteam/school-information-system/assets/22511259/e85d5915-c133-4801-a8fb-1990efab1336)

**Comment by smaker** [comment]
@devgoodway PC/모바일에서 스타일 수정하여 다시 커밋했습니다. 확인 부탁드릴게요!

**Comment by devgoodway** [comment]
> @devgoodway PC/모바일에서 스타일 수정하여 다시 커밋했습니다. 확인 부탁드릴게요!

네 확인했습니다. 수고하셨습니다.
