### ISSUE TITLE
[BUG] : 구글 로그인 오류

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#94]
**Description**
iampassion@bmrschool.org
계정으로 로그인 시 아래와 같은 문제가 발생하면서 접속이 안되고 있음.

**스크린샷**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/22511259/216525230-a2553c7a-a6bf-49ac-b872-d3fe31ee7cbf.png">

**기타 사항**

**Comment by jessie129j** [comment]
해당 계정의 snsId 필드가 누락되어있었습니다. db 데이터 수정했으니 바로 다시 시도해도 될 것 같습니다

**Comment by devgoodway** [comment]
> 

아 그 문제였구나 땡큐!
