### ISSUE TITLE
[BUG] : snsId 등록 오류

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#95]
**Description**
사용자 등록시에 snsID가 등록되지 않습니다.

**스크린샷**
단일 사용자 등록 결과
<img width="1171" alt="image" src="https://user-images.githubusercontent.com/22511259/216968099-8d8dccd8-10c0-44d0-8441-a1f054f3b984.png">

일괄 사용자 등록 결과
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/22511259/216968604-3d3400a9-0ccd-49cd-9158-5a9400928676.png">

**기타 사항**

**Comment by jessie129j** [comment]
설계할 때 사용자 등록시에 자동으로 snsId가 등록되지 않고 사용자가 직접 연동하도록 하기로 했었습니다. 아직 [구글 로그인 연동] 부분이 구현되지 않은 상태입니다.

**Comment by devgoodway** [comment]
아 그러면 지금 등록된 사용자들은 구글로 로그인 할 수 없는거죠?
인증 과정을 생략하면 사용자 등록 시에 구글 아이디를 입력 할 수 있도록 해도 되지 않을까요?

**Comment by jessie129j** [comment]
> 아 그러면 지금 등록된 사용자들은 구글로 로그인 할 수 없는거죠?

그쵸! 사용자 등록시에 입력한 이메일은 email 필드에 저장되고 자동으로 snsId.google로 등록되는게 아니니까요

> 인증 과정을 생략하면 사용자 등록 시에 구글 아이디를 입력 할 수 있도록 해도 되지 않을까요?

가능이야 한데 회의때 그렇게 하지 않기로 했던걸로 기억해요. 그럼 관리자가 사용자 생성/수정/일괄 생성시 snsId를 등록할 수 있도록 다시 수정할까요?
아직 눈이 코딩할 상태는 아니라 시간은 좀 걸릴 갓 같아요.

**Comment by devgoodway** [comment]
관리자가 책임지고 등록 할 수 있도록 하면 될 것 같아서 나중에 괜찮아지면 부탁하고
지금 등록한 데이터는 내가 수정해서 접속 할 수 있도록 할께
