### ISSUE TITLE
[BUG] : 수강 신청 등록 순서 오류

### ISSUE THREAD

**Issue by devgoodway** [devgoodway/school-information-system#97]
**Description**
등록 명단의 리스트가 신청 된 순서대로 출력되지 않는 문제

**스크린샷**
등록 명단
![Screenshot 2023-02-09 5 57 13 PM](https://user-images.githubusercontent.com/22511259/217785843-db175dd2-4c2a-45cd-b78d-a865bff7e909.png)

데이터베이스 상 등록 순서
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/22511259/217785476-f2ebc558-e731-45d8-90dd-fddfd2a1bd73.png">

**기타 사항**

**Comment by jessie129j** [comment]
1. 수강자 명단을 신청 순서나 이름순으로 불러와야 한다는 기준이 없었던 것 같은데 오류로 봐야 하나요?
2. 기준 정해주시면 명단 불러오는 API 또는 API 호출 부분 수정하겠습니다! 
3. limit이 6명으로 제한된 수업인데 초과해서 수강신청이 된건가요?

**Comment by devgoodway** [comment]
1. 명시를 따로 하지는 않았는데 기존 시스템이 등록순이었고 번호가 있어서 혼동이 되는 것 같아요
2. 등록순서대로 가장 빠른 것이 1번이 되도록 하면 됩니다
3. 초과 신청이 된 것은 아닙니다

**Comment by jessie129j** [comment]
수정했습니다

**Comment by jessie129j** [comment]
아직 멘토링 페이지에서는 반영이 안되는 것 같네요. 해당 부분 수정하겠습니다.

**Comment by jessie129j** [comment]
수정되었습니다

**Comment by devgoodway** [comment]
수고했어요 차순이 역순으로 나와서 수정했어요
